name: 1.58-bitnet
type: gradio-space
sdk: gradio

metadata:
  space_id: Chris4K/1.58-bitnet
  original_url: https://huggingface.co/spaces/Chris4K/1.58-bitnet

deploy:
  targets:
    - public-repo
    - huggingface

build:
  command: bash build.sh

test:
  command: echo "Tests not yet implemented"
